[package]
name = "paired"

# Remember to change version string in README.md.
version = "0.15.1"
authors = [
    "Sean Bowe <ewillbefull@gmail.com>",
    "Jack Grigg <jack@z.cash>",
]
license = "MIT/Apache-2.0"

description = "Pairing-friendly elliptic curve library"
documentation = "https://docs.rs/paired/"
homepage = "https://github.com/filecoin-project/paired"
repository = "https://github.com/filecoin-project/paired"

[dependencies]
rand = "0.4"
byteorder = "1"
ff = { git = "https://github.com/filecoin-project/ff", branch = "feat/asm", features = ["derive"] }
blake2b_simd = "0.5"
serde = { version = "1.0", optional = true, features = ["derive"] }

[features]
unstable-features = ["expose-arith"]
expose-arith = []
default = []

[dev-dependencies]
serde_json = "1.0"
